[package]
name = "gung"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "An embedded Intranet penetration tool, supports multiple protocols and Python script plugins."
readme = "README.md"
repository = "https://github.com/Poseidon-fan/Gung"
keywords = ["proxy", "nat-traversal", "tunnel", "python-plugin"]
categories = ["network-programming", "asynchronous", "command-line-utilities"]

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
atty = { workspace = true }
toml = { workspace = true }

server = { path = "../server" }
client = { path = "../client" }
config = { path = "../components/config" }

[[bin]]
name = "gungs"
path = "src/bin/server.rs"

[[bin]]
name = "gungc"
path = "src/bin/client.rs"
