name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Cross build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cross: false
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            cross: false
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            cross: true
          - os: ubuntu-latest
            target: arm-unknown-linux-musleabi
            cross: true
          - os: ubuntu-latest
            target: arm-unknown-linux-musleabihf
            cross: true
          - os: ubuntu-latest
            target: armv7-unknown-linux-musleabihf
            cross: true
          - os: ubuntu-latest
            target: mips-unknown-linux-gnu
            cross: true
          - os: ubuntu-latest
            target: mips-unknown-linux-musl
            cross: true
          - os: ubuntu-latest
            target: mipsel-unknown-linux-gnu
            cross: true
          - os: ubuntu-latest
            target: mipsel-unknown-linux-musl
            cross: true
          - os: ubuntu-latest
            target: mips64-unknown-linux-gnuabi64
            cross: true
          - os: ubuntu-latest
            target: mips64el-unknown-linux-gnuabi64
            cross: true
          - os: macos-latest
            target: x86_64-apple-darwin
            cross: false
          - os: macos-latest
            target: aarch64-apple-darwin
            cross: false
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            cross: false

    steps:
      - uses: actions/checkout@v5
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          default: true

      # Native build
      - name: Install target
        if: matrix.cross == false
        run: rustup target add ${{ matrix.target }}
      - name: Build release (native)
        if: matrix.cross == false
        run: cargo build --release --target ${{ matrix.target }}

      # Cross build
      - name: Install cross
        if: matrix.cross
        run: cargo install --version 0.2.5 cross
      - name: Build release (cross)
        if: matrix.cross
        run: cross build --release --target ${{ matrix.target }}

      - name: Run UPX
        continue-on-error: true
        if: matrix.os == 'ubuntu-latest' && !contains(matrix.target, 'mips')
        uses: crazy-max/ghaction-upx@v1
        with:
          version: v4.0.2
          files: |
            target/${{ matrix.target }}/release/gungs${{ matrix.os == 'windows-latest' && '.exe' || '' }}
            target/${{ matrix.target }}/release/gungc${{ matrix.os == 'windows-latest' && '.exe' || '' }}
          args: -q --best --lzma

      - uses: actions/upload-artifact@v4
        with:
          name: gung-tools-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/gungs${{ matrix.os == 'windows-latest' && '.exe' || '' }}
            target/${{ matrix.target }}/release/gungc${{ matrix.os == 'windows-latest' && '.exe' || '' }}

      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.1
        with:
          type: zip
          filename: gung-tools-${{ matrix.target }}.zip
          directory: target/${{ matrix.target }}/release/
          path: |
            gungs${{ matrix.os == 'windows-latest' && '.exe' || '' }}
            gungc${{ matrix.os == 'windows-latest' && '.exe' || '' }}

      - name: Publish
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/${{ matrix.target }}/release/gung-tools-${{ matrix.target }}.zip
          generate_release_notes: true
          draft: true
