name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    permissions:
      contents: write
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - uses: actions/checkout@v5
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          default: true

      # Setup Python environment
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Build
      - name: Install target
        run: rustup target add ${{ matrix.target }}
      - name: Build release
        run: cargo build --release --target ${{ matrix.target }}

      - name: Run UPX
        continue-on-error: true
        if: matrix.os == 'ubuntu-latest'
        uses: crazy-max/ghaction-upx@v1
        with:
          version: v4.0.2
          files: |
            target/${{ matrix.target }}/release/gungs${{ matrix.os == 'windows-latest' && '.exe' || '' }}
            target/${{ matrix.target }}/release/gungc${{ matrix.os == 'windows-latest' && '.exe' || '' }}
          args: -q --best --lzma

      - uses: actions/upload-artifact@v4
        with:
          name: gung-tools-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/gungs${{ matrix.os == 'windows-latest' && '.exe' || '' }}
            target/${{ matrix.target }}/release/gungc${{ matrix.os == 'windows-latest' && '.exe' || '' }}

      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.1
        with:
          type: zip
          filename: gung-tools-${{ matrix.target }}.zip
          directory: target/${{ matrix.target }}/release/
          path: |
            gungs${{ matrix.os == 'windows-latest' && '.exe' || '' }}
            gungc${{ matrix.os == 'windows-latest' && '.exe' || '' }}

      - name: Publish
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/${{ matrix.target }}/release/gung-${{ matrix.target }}.zip
          generate_release_notes: true
          draft: true
