[package]
name = "transport"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
async-trait = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
quinn = { workspace = true }
net-mux = { workspace = true }
rustls = { workspace = true }
rustls-native-certs = { workspace = true }

[[example]]
name = "transport_server"
path = "examples/server.rs"

[[example]]
name = "transport_client"
path = "examples/client.rs"
