[package]
name = "transport"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
async-trait = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
quinn = { workspace = true }
net-mux = { workspace = true }
rustls = { workspace = true }
rustls-native-certs = { workspace = true }
tokio_kcp = { workspace = true }
tokio-tungstenite = { workspace = true }
futures-util = { workspace = true }
bytes = { workspace = true }
tokio-util = { workspace = true }
config = { path = "../config" }
cert = { path = "../cert" }

[[example]]
name = "transport_server"
path = "examples/server.rs"

[[example]]
name = "transport_client"
path = "examples/client.rs"
